### PR TITLE
promises

### PR DESCRIPTION
**Pull request by UziTech**
Async functions return a promise unless a callback is provided

### CODE REVIEW

**Comment by UziTech** [comment]
@miguelsolano This would be a big improvement. To be able to use promises and async/await.

This is fully backwards compatible. If a callback is given the asynchronous functions act the same as before. If no callback is given they return a promise instead of undefined.

Can we get this merged?

**Comment by paulmelnikow** [comment]
Hi @UziTech, I wonder if you've seen https://github.com/benjamingr/tmp-promise. It's an established solution that wraps this library, and is widely used. It has an expressive interface that includes a cleanup function, and a few tests.

What do you think about that interface?

(See benjamingr/tmp-promise#36)

**Comment by UziTech** [comment]
I believe [`tmp-promise`](https://www.npmjs.com/package/tmp-promise) wraps [`tmp`](https://www.npmjs.com/package/tmp) not [`temp`](https://www.npmjs.com/package/temp).

**Comment by paulmelnikow** [comment]
Ha! You're right.

**Pull request merged**
